# Generated by Django 5.0.4 on 2024-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
